language: c

sudo: false

cache:
  directories:
  - $HOME/.racket/download-cache

env:
- PATH=~/racket/bin:$PATH

before_install:
- export PKG=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2`
- echo $PKG
- curl -L -o installer.sh http://plt.eecs.northwestern.edu/snapshots/current/installers/min-racket-current-x86_64-linux-precise.sh
- sh installer.sh --in-place --dest ~/racket/
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"

install:
- raco pkg install -i --deps search-auto compiler-lib # for `raco test`
- racket -l- pkg/dirs-catalog --link --check-metadata pkgs-catalog .
- echo file://`pwd`/pkgs-catalog/ > catalog-config.txt
- raco pkg config catalogs >> catalog-config.txt
- raco pkg config --set catalogs `cat catalog-config.txt`
- raco pkg install -i --deps search-auto $PKG-test
- ls $HOME/.racket/download-cache

script:
- raco test -p $PKG-lib
- raco test -p $PKG-doc
- raco test -p $PKG-test
